"""auto increment ids

Revision ID: 594c9183cc0f
Revises: f56061dbada6
Create Date: 2020-08-19 13:08:50.253607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c9183cc0f'
down_revision = 'f56061dbada6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
