version: "3"
services:
  db:
    image: postgres
    restart : always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - medwatch:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  medwatch: